services:
    laravel.test:
        container_name: weather-app
        build:
            context: .
            dockerfile: ./docker/8.3/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
            - '5173:5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-develop,debug}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal start_with_request=yes idekey=docker}'
            PHP_IDE_CONFIG: "serverName=docker-weather"
        volumes:
            - '.:/var/www/html'
        networks:
            - weather-app
        depends_on:
            - mysql

    mysql:
        container_name: weather-mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3316:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'weather-mysql:/var/lib/mysql'
        networks:
            - weather-app

    mysql-test:
        container_name: weather-mysql-test
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'secret_test'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'weather_test'
            MYSQL_USER: 'weather_test'
            MYSQL_PASSWORD: 'secret_test'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        tmpfs:
            - /var/lib/mysql:rw
        networks:
            - weather-app
networks:
    weather-app:
        driver: bridge

volumes:
    weather-mysql:
        driver: local
